quote steveive8's Deep-Learning-Zero-To-All-2-PyTorch, Lab 1: Tensor Manipulation

## Import

In [ ]:
import numpy as np
import torch

## Numpy

In [ ]:
# 1D array
na = np.array([ 0., 1., 2., 3., 4., 5., 6. ])
print(na)
print("Rank of na :", na.ndim)
print("Shape of na :", na.shape)

print("na[0] na[1] na[2] =", na[0], na[1], na[2])
print("na[2:5] na[4:-1] =", na[2:5], na[4:-1])
print("na[:2] na[3:] =", na[:2], na[3:])
print()

# 2D array
li = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(li)
print("Rank of li :", li.ndim)
print("Shape of li :", li.shape)


[0. 1. 2. 3. 4. 5. 6.]
Rank of na : 1
Shape of na : (7,)
na[0] na[1] na[2] = 0.0 1.0 2.0
na[2:5] na[4:-1] = [2. 3. 4.] [4. 5.]
na[:2] na[3:] = [0. 1.] [3. 4. 5. 6.]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of li : 2
Shape of li : (4, 3)


# PyTorch

## 1D Array with PyTorch

In [ ]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


##t.size() & t.shape
- PyTorch에서는 t.size()는 tensor에서 전체 elementsdml 양(amount)을 알려준다...!

In [ ]:
print('rank :',t.dim())
print('Shape(using shape) :',t.shape)
print('Shape(using size) :',t.size())
print("We can check t's element using index number : t[0]",t[0],"t[1]",t[1],"t[-1]",t[-1] )
print('Slicing : t[2:5]',t[2:5],'t[:2]',t[:2],'t[3:]',t[3:])
print('Size with dim : t.size(dim=0)',t.size(dim=0))

rank : 1
Shape(using shape) : torch.Size([7])
Shape(using size) : torch.Size([7])
We can check t's element using index number : t[0] tensor(0.) t[1] tensor(1.) t[-1] tensor(6.)
Slicing : t[2:5] tensor([2., 3., 4.]) t[:2] tensor([0., 1.]) t[3:] tensor([3., 4., 5., 6.])
Size with dim : t.size(dim=0) 7


## 2D Array with PyTorch

In [ ]:
t = torch.FloatTensor([[1.,2.,3.,],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])

print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print('Rank :',t.dim)
print('Shape :',t.size())
print('Slicing t[:, 2] =', t[:, 2])
print('t[:, 2] size :',t[:,2].size())
print(t[:, :-1])

Rank : <built-in method dim of Tensor object at 0x7fc2fb251550>
Shape : torch.Size([4, 3])
Slicing t[:, 2] = tensor([ 3.,  6.,  9., 12.])
t[:, 2] size : torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Shape, Rank, Axis

In [ ]:
t = torch.FloatTensor([[[[1.,2.,3.,4.],
                        [5.,6.,7.,8.],
                        [9.,10.,11.,12.]],
                       
                       [[13.,14.,15.,16.],
                        [17.,18.,19.,20.],
                        [21.,22.,23.,24.]]
                        ]])

In [ ]:
print(t)
print('t.dim()',t.dim())
print('t.size()',t.size())

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])
t.dim() 4
t.size() torch.Size([1, 2, 3, 4])


## Broadcasting

In [ ]:
# Same shape
m1 = torch.FloatTensor([[5,5]])
m2 = torch.FloatTensor([[8,8]])

print('m1 + m2 =', m1+m2)

m1 + m2 = tensor([[13., 13.]])


In [ ]:
# Vector + Scalar
v1 = torch.FloatTensor([94, 92])
s1 = torch.FloatTensor([2]) # 2 -> [[2],[2]]

print('v1 + s1 =', v1+s1)

v1 + s1 = tensor([96., 94.])


In [ ]:
# 1 * 2 Vector + 2 * 1 Vector
v2 = torch.FloatTensor([[4,5]])
v3 = torch.FloatTensor([[2],[1]])
print('v2 + v3 =', v2+v3)

v2 + v3 = tensor([[6., 7.],
        [5., 6.]])


# Operations in PyTorch

## Multiplation(elementwise multiplication) Vs MatMul(Inner product == Dot product)

In [ ]:
print()
print()
print('Multiplation Vs MatMul')
print()
print()
print("--------Mul--------")
m3 = torch.FloatTensor([[1,3],[2,4]])
m4 = torch.FloatTensor([[5],[6]])
print('Shape of Matrix 3:', m3.shape) 
print('Shape of Matrix 4:', m4.shape) 
print('m3 * m4 =') 
print(m3*m4) # broadcasting -> 2 * 2
print('Mul; m3.mul(m4) = ')
print(m3.mul(m4))
print()
print()
print("-------MatMul-------")
m5 = torch.FloatTensor([[1,3],[2,4]]) 
m6 = torch.FloatTensor([[5],[6]])
print('Shape of Matrix 5:', m5.shape) # 2 * 2
print('Shape of Matrix 6:', m6.shape) # 2 * 1
print('MatMul; m5.matmul(m6) = ')
print(m5.matmul(m6))




Multiplation Vs MatMul


--------Mul--------
Shape of Matrix 3: torch.Size([2, 2])
Shape of Matrix 4: torch.Size([2, 1])
m3 * m4 =
tensor([[ 5., 15.],
        [12., 24.]])
Mul; m3.mul(m4) = 
tensor([[ 5., 15.],
        [12., 24.]])


-------MatMul-------
Shape of Matrix 5: torch.Size([2, 2])
Shape of Matrix 6: torch.Size([2, 1])
MatMul; m5.matmul(m6) = 
tensor([[23.],
        [34.]])


## Mean

In [ ]:
t = torch.FloatTensor([3,6])
print('Mean :',t.mean())

Mean : tensor(4.5000)


In [ ]:
# Can't use mean() on integers !
t = torch.LongTensor([2, 7])

try:
  print('Mean :', t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [ ]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print('t.mean() :', t.mean())
print('t.mean(dim = 0) :', t.mean(dim=0))
print('t.mean(dim = 1) :', t.mean(dim=1))
print('t,mean(dim = -1) :', t.mean(dim=-1))

t.mean() : tensor(2.5000)
t.mean(dim = 0) : tensor([2., 3.])
t.mean(dim = 1) : tensor([1.5000, 3.5000])
t,mean(dim = -1) : tensor([1.5000, 3.5000])


## Sum

In [ ]:
t = torch.FloatTensor([[1,5],[2,7]])
print(t)

tensor([[1., 5.],
        [2., 7.]])


In [ ]:
print('t.sum() :')
print(t.sum())
print()
print('t.sum(dim=0) :')
print(t.sum(dim=0))
print()
print('t.sum(dim=1) :')
print(t.sum(dim=1))
print()
print('t.sum(dim=-1)')
print(t.sum(dim=-1))

t.sum() :
tensor(15.)

t.sum(dim=0) :
tensor([ 3., 12.])

t.sum(dim=1) :
tensor([6., 9.])

t.sum(dim=-1)
tensor([6., 9.])


## Max & Argmax

In [ ]:
t = torch.FloatTensor([[2,6],[9,3]])
print(t)

tensor([[2., 6.],
        [9., 3.]])


The max() operator returns done value if it is called without an argument.

In [ ]:
print('t.max() :', t.max()) #Returns one value: max

t.max() : tensor(9.)


The max operatorreturn 2 values when called with dimension specified. The first values is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [ ]:
print('t.max(dim=0) :')
print(t.max(dim=0)) #Returns two values : max and argmax
print()
print('Max :', t.max(dim=0)[0])
print('Argmax :', t.max(dim=0)[1])

t.max(dim=0) :
torch.return_types.max(
values=tensor([9., 6.]),
indices=tensor([1, 0]))

Max : tensor([9., 6.])
Argmax : tensor([1, 0])


In [ ]:
print('t.max(dim=1)')
print(t.max(dim=1))
print()
print('t.max(dim=-1)')
print(t.max(dim=-1))

t.max(dim=1)
torch.return_types.max(
values=tensor([6., 9.]),
indices=tensor([1, 0]))

t.max(dim=-1)
torch.return_types.max(
values=tensor([6., 9.]),
indices=tensor([1, 0]))


## View
* view ➡️ Reshape

In [ ]:
t = np.array([[[0,1,2],
               [3,4,5]],
              
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
print('ft.view([-1,1,3])')
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

ft.view([-1,1,3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

* tensor.squeeze(dim)

* Removes the dimension where the size is 1 in a tensor
* Argument gets the dimension of tensor which to be squeezed

In [ ]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze 

* tensor.unsqueeze(dim)

* Add the dimension whaere the size is 1 in a tensor
* Argument gets the dimension of tensor which to be unsqueezed

In [ ]:
ft = torch.Tensor([0,1,2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


We can make same effect for the dimension with ft.view()

In [ ]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Scatter ( for one-hot encoding )

* tensor.scatter_(dim, index, src)
* Write all element by src in Tensor with indicies of index with the corresponding dimension

In [ ]:
lt = torch.LongTensor([[0],[1],[2],[0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [ ]:
onehot = torch.zeros(4,3) #batch size = 4, classes = 3
onehot.scatter_(1,lt,1)
print(onehot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


## Casting

In [ ]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


## Concatenation

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [ ]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

* Creating dimension of number of elements in the list at the corresponding dimension of concatinated matrix

In [ ]:
x = torch.FloatTensor([1,4]) #(2, )
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [ ]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)],dim=0))
print(torch.cat([x.unsqueeze(1),y.unsqueeze(1),z.unsqueeze(1)],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## One & Zero Like

In [ ]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])

In [ ]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Zip

In [ ]:
for x,y in zip([1,2,3],[4,5,6]):
  print(x,y)

1 4
2 5
3 6


In [ ]:
for x,y,z in zip([1,3,5],[2,4,6],[3,7,11]):
  print(x,)