# Linear Regression

- $H(X)$: Hypothesis of given $x$ value. 주어진 값에 대한 예측
- $cost(W,b)$: $H(x)$가 y와 일치하는 정도. 얼마나 잘 예측했는지를 표현하는 값.

# Import

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

### What is ```torch.manual_seed()```?!?!
- 동일 실험 진행을 위해서는 동일한 난수사용이 필요하다. 
```random.rand()```는 항상 다른 난수 집합이 형성되지만, ```manual_seed```를 사용하면 동일한 난수가 형성된다.

In [6]:
torch.manual_seed(1)

# Data

기본적으로 pytorch는 NCHW format을 가지고 있다.
첫 단계인 사전처리를 실행. 이미지 형식을 NCHW 형식으로 변환한다.
NCHW는 배치(batch-N), 채널(channals-C), 깊이(depth-D), 높이(height-H), 폭(width-W)를 나타낸다.
다차원 배열, 데이터프레임, 행렬을 1-D array로 저장하는 방법이다.(다차원을 하나로 "casting"하는 방법 중 하나이다.)


In [7]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

In [8]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [9]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


# Weight Initialization

```requires_grad = True```는 ```autograd```에 모든 연산을 추적하도록 한다.

In [10]:
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [11]:
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


# Hypothesis

$H(x) = Wx +b$

In [12]:
hypothesis =  x_train*W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


# Cost Function

$cost(W,b) = \frac{1}{m} \sum^m_{i=1}( H(x^{(i)}) - y^{(i)})^2$

In [14]:
print(hypothesis)
print(y_train)
print(hypothesis - y_train)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor([[1.],
        [2.],
        [3.]])
tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [15]:
print((hypothesis - y_train)**2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [16]:
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


# Gradient Descent

In [18]:
#  최적화(optimizer)를 위한 확률적 경사하강법의 사용(SGD; Stochastic Gradient Descent)
optimizer = optim.SGD([W,b],lr=0.01) 

In [19]:
optimizer.zero_grad()
cost.backward() #현재 tensor의 기울기를 계산
optimizer.step() #single optimization step 수행

In [20]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [21]:
#hypothesis 비교

hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [22]:
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


# Full-code

 간단한 loop의 사용을 통해 다수의 epochs으로 학습을 진행 할 수 있다.

In [29]:
#Data
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

#Model Initialization
W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

#Set optimizer
optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1000

for epoch in range(nb_epochs+1):

    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch %100 == 0:
        print('Epoch {:4d}/{} W = {:.3f}, b= {:.3f}, cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1000 W = 0.093, b= 0.040, cost: 4.666667
Epoch  100/1000 W = 0.873, b= 0.289, cost: 0.012043
Epoch  200/1000 W = 0.900, b= 0.227, cost: 0.007442
Epoch  300/1000 W = 0.921, b= 0.179, cost: 0.004598
Epoch  400/1000 W = 0.938, b= 0.140, cost: 0.002842
Epoch  500/1000 W = 0.951, b= 0.110, cost: 0.001756
Epoch  600/1000 W = 0.962, b= 0.087, cost: 0.001085
Epoch  700/1000 W = 0.970, b= 0.068, cost: 0.000670
Epoch  800/1000 W = 0.976, b= 0.054, cost: 0.000414
Epoch  900/1000 W = 0.981, b= 0.042, cost: 0.000256
Epoch 1000/1000 W = 0.985, b= 0.033, cost: 0.000158


# Using ```nn.Module```

In [36]:
#Data
x_train_ = torch.FloatTensor([[1],[2],[3]])
y_train_ = torch.FloatTensor([[1],[2],[3]])


#build linear regression model
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)


model = LinearRegressionModel()

#Hypothesis 
#Hypothesis > return forward of nn.Module
hypothesis_ = model(x_train)
print(list(model.parameters()))
print(hypothesis_)

#Cost
print(hypothesis_)
print(y_train)

cost = F.mse_loss(hypothesis_, y_train) #MSE(Mean Squared Error) PyTorch에서 제공
print(cost)

#Gradient Descent
optimizer_ = optim.SGD(model.parameters(),lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

[Parameter containing:
tensor([[0.2774]], requires_grad=True), Parameter containing:
tensor([0.0493], requires_grad=True)]
tensor([[0.3267],
        [0.6041],
        [0.8814]], grad_fn=<AddmmBackward>)
tensor([[0.3267],
        [0.6041],
        [0.8814]], grad_fn=<AddmmBackward>)
tensor([[1.],
        [2.],
        [3.]])
tensor(2.2968, grad_fn=<MseLossBackward>)


In [38]:
# Using loop

x_train_=torch.FloatTensor([[1],[2],[3]])
y_train_=torch.FloatTensor([[1],[2],[3]])

model=LinearRegressionModel()

optimizer = optim.SGD(model.parameters(),lr=0.01)
nb_epochs = 1000

for epoch in range(nb_epochs+1):

    #hypothesis
    pred=model(x_train_)

    #cost
    cost=F.mse_loss(pred,y_train_)

    #optimize the cost
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        para = list(model.parameters())
        w = para[0].item()
        b = para[1].item()

        print('Epoch {:4d}/{} w:{:.3f} b:{:.3f} Cost:{:.6f}'.format(epoch,nb_epochs,w,b,cost.item()))

Epoch    0/1000 w:0.031 b:-0.045 Cost:5.766424
Epoch  100/1000 w:0.890 b:0.251 Cost:0.009079
Epoch  200/1000 w:0.913 b:0.197 Cost:0.005610
Epoch  300/1000 w:0.932 b:0.155 Cost:0.003467
Epoch  400/1000 w:0.946 b:0.122 Cost:0.002142
Epoch  500/1000 w:0.958 b:0.096 Cost:0.001324
Epoch  600/1000 w:0.967 b:0.075 Cost:0.000818
Epoch  700/1000 w:0.974 b:0.059 Cost:0.000505
Epoch  800/1000 w:0.980 b:0.047 Cost:0.000312
Epoch  900/1000 w:0.984 b:0.037 Cost:0.000193
Epoch 1000/1000 w:0.987 b:0.029 Cost:0.000119
